language: go
go:
- '1.8'
script:
  - 'make bareback'
deploy:
  provider: releases
  api_key:
    secure: "YhZA8GjGCyeixr9NEboFnrHRp7eBFwIL9bpiBXsOLtbUgUpJCt7PMAiilaARNaBhDEeZG0hhDbF1fncaigZ+uMDlBu1FaSbf33eAe7J5bQmCFVA6Rjb/YqJteljgRyb6OtXAs9MvgNmH+hzTDyOrUPq7wt2b6A84gfC7bzR6G5cW1AGCA72/bM4h7Zy92DjWdx9c7p7GzxrWlf6vvcZyi5CnWqDU+7DiTsMnJMipKpjJa3ELcaFKdWZzBpH25DMEzT/SRGc3mn0qmUDVfu6ie9HJbnfAmmZ1bEiiWmy0icOskGsLbnod9W6Das+r4QXOfKm4/Hcx8lGTNexX85/LG01wggTcmVv8W1LuKJW2a/Scv0P5SJPtHgxktW4FSmnexCVodvmZT1c5Cu6ql2h7BQgJKePFjJc1FWg1ri0sG2DoF1bBDcFn8ekyoz+E1+sRQqwtR6Z09gnSurT/4nrpOPIDFiFyXRHvqbhR505hvi0L5ZnS+G74PWGFgTq5JULxWlzgLpBpJBjKPrdLA522ttbmu/lBsXYU69F3rsw0mKg/nMkhJU78hrJg7s+cwkLnONsmEjY2HbJfkveA5isxdKIzjNqAepuYps/wGWJmDh3kDCcNIIlviAg9W5P478Sct9iGC0tpwvcwNoD4co46k7z0ONAhs+JD77+75VMllf0="
  file_glob: true
  file: output/*.tar.gz
  skip_cleanup: true
  on:
    repo: GESkunkworks/sesame-seed
    tags: true
